### ISSUE TITLE
Put all projects on the front page

### ISSUE THREAD

**Issue by chshersh** [Holmusk/holmusk.github.io#22]
Currently there's only `elm-street`. But we can also put:

- [x] `elm-street`
- [x] `servant-hmac-auth`
- [x] `fcm-client`
- [x] `three-layer`
- [x] `timed-cache`
- [x] `elmoji`
- [x] `s3_cache_image`

And we also can think of some nice design for the projects. For example, add small logo of the programming language to each entry to indicate what language it is written it.

I think this will improve the quality of the landing page by showing how many open-source projects do we have.

**Comment by arbus** [comment]
Lets come up with a short description of all the projects so that Yunus can make the sketches

**Comment by chshersh** [comment]
For projects that I'm aware of:

+ `elm-street`: https://github.com/holmusk/elm-street#what-this-library-about
    Also: `Crossing the road between Haskell and Elm`
    **_Inspiration:_** I assume that some clever combination of Haskell and Elm logos can work as an illustration for this project
+ `servant-hmac-auth`: Library that provides protection of all servant endpoints with HMAC scheme. 
    **_Inspiration:_** Maybe `servant` logo + some key or other crypto stuff
+ `fcm-client`: Haskell Client for FCM.
    **_Inspiration:_** Again, Haskell logo + FCM logo should work just fine 👍 
+ `three-layer`: Haskell application architecture based on the Three Layer Cake programming pattern.
    **_Inspiration:_** Three layer cake is kinda speaks for itself 😄
